/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CampaignResponse"][];
                        "application/json": components["schemas"]["CampaignResponse"][];
                        "text/json": components["schemas"]["CampaignResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Campaign"];
                    "text/json": components["schemas"]["Campaign"];
                    "application/*+json": components["schemas"]["Campaign"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CampaignResponse"];
                        "application/json": components["schemas"]["CampaignResponse"];
                        "text/json": components["schemas"]["CampaignResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Campaigns/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CampaignResponse"];
                        "application/json": components["schemas"]["CampaignResponse"];
                        "text/json": components["schemas"]["CampaignResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Campaigns/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": string[];
                    "text/json": string[];
                    "application/*+json": string[];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Campaigns/{id}/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddCompaniesToCampaignRequest"];
                    "text/json": components["schemas"]["AddCompaniesToCampaignRequest"];
                    "application/*+json": components["schemas"]["AddCompaniesToCampaignRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Companies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    CompanyName?: string;
                    Address?: string;
                    City?: string;
                    State?: string;
                    Zip?: string;
                    Country?: string;
                    WebsiteUrl?: string;
                    Type?: string;
                    TaxId?: string;
                    PrimaryRepName?: string;
                    LegacyPrimaryCategory?: string;
                    HubspotCompanyId?: number;
                    Collections?: boolean;
                    WriteOff?: boolean;
                    Dead?: boolean;
                    IsNewCompany?: boolean;
                    CompanySpecialBilling?: boolean;
                    Page?: number;
                    PageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyResponse"][];
                        "application/json": components["schemas"]["CompanyResponse"][];
                        "text/json": components["schemas"]["CompanyResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCompanyRequest"];
                    "text/json": components["schemas"]["CreateCompanyRequest"];
                    "application/*+json": components["schemas"]["CreateCompanyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyResponse"];
                        "application/json": components["schemas"]["CompanyResponse"];
                        "text/json": components["schemas"]["CompanyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyResponse"];
                        "application/json": components["schemas"]["CompanyResponse"];
                        "text/json": components["schemas"]["CompanyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactResponse"][];
                        "application/json": components["schemas"]["ContactResponse"][];
                        "text/json": components["schemas"]["ContactResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateContactRequest"];
                    "text/json": components["schemas"]["CreateContactRequest"];
                    "application/*+json": components["schemas"]["CreateContactRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactResponse"];
                        "application/json": components["schemas"]["ContactResponse"];
                        "text/json": components["schemas"]["ContactResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactResponse"];
                        "application/json": components["schemas"]["ContactResponse"];
                        "text/json": components["schemas"]["ContactResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/EmailMarketing/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SendEmailRequest"];
                    "text/json": components["schemas"]["SendEmailRequest"];
                    "application/*+json": components["schemas"]["SendEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SendEmailResponse"];
                        "application/json": components["schemas"]["SendEmailResponse"];
                        "text/json": components["schemas"]["SendEmailResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateIntegrationRequest"];
                    "text/json": components["schemas"]["CreateIntegrationRequest"];
                    "application/*+json": components["schemas"]["CreateIntegrationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IntegrationResponse"];
                        "application/json": components["schemas"]["IntegrationResponse"];
                        "text/json": components["schemas"]["IntegrationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Integrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IntegrationResponse"];
                        "application/json": components["schemas"]["IntegrationResponse"];
                        "text/json": components["schemas"]["IntegrationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddCompaniesToCampaignRequest: {
            companyIds?: string[] | null;
            primaryContactsOnly?: boolean;
            companyContactRoleIds?: number[] | null;
        };
        Campaign: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
            status?: components["schemas"]["CampaignStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            campaignContacts?: components["schemas"]["CampaignContact"][] | null;
        };
        CampaignActivity: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            campaignContactId?: string;
            campaignContact?: components["schemas"]["CampaignContact"];
            activityType?: components["schemas"]["CampaignActivityType"];
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
            events?: components["schemas"]["CampaignActivityEvent"][] | null;
        };
        CampaignActivityEvent: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            campaignActivityId?: string;
            campaignActivity?: components["schemas"]["CampaignActivity"];
            type?: components["schemas"]["CampaignActivityEventType"];
            notes?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @enum {string} */
        CampaignActivityEventType: "Created" | "Sent" | "Delivered" | "Opened" | "Clicked" | "Unsubscribed" | "Bounced" | "Attempted" | "Connected" | "VoicemailLeft" | "CallbackRequested" | "Failed";
        /** @enum {string} */
        CampaignActivityType: "Email" | "Call" | "Note";
        CampaignContact: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            campaignId?: string;
            campaign?: components["schemas"]["Campaign"];
            /** Format: uuid */
            contactId?: string;
            contact?: components["schemas"]["Contact"];
            /** Format: date-time */
            assignedAt?: string;
            activities?: components["schemas"]["CampaignActivity"][] | null;
        };
        CampaignContactResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            campaignId?: string;
            /** Format: uuid */
            contactId?: string;
            contact?: components["schemas"]["ContactResponse"];
            /** Format: date-time */
            assignedAt?: string;
        };
        CampaignResponse: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
            status?: components["schemas"]["CampaignStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            contacts?: components["schemas"]["CampaignContactResponse"][] | null;
        };
        /** @enum {string} */
        CampaignStatus: "Draft" | "Active" | "Completed";
        Company: {
            /** Format: uuid */
            id?: string;
            companyName?: string | null;
            address?: string | null;
            address2?: string | null;
            city?: string | null;
            state?: string | null;
            zip?: string | null;
            country?: string | null;
            websiteUrl?: string | null;
            type?: string | null;
            taxId?: string | null;
            /** Format: date-time */
            lastUpdate?: string | null;
            collections?: boolean;
            writeOff?: boolean;
            primaryRepName?: string | null;
            legacyPrimaryCategory?: string | null;
            /** Format: int64 */
            hubspotCompanyId?: number | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            /** Format: date-time */
            createdDate?: string | null;
            isActive?: boolean;
            isNewCompany?: boolean;
            companySpecialBilling?: boolean | null;
            companyContacts?: components["schemas"]["CompanyContact"][] | null;
        };
        CompanyContact: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            companyId?: string;
            company?: components["schemas"]["Company"];
            /** Format: uuid */
            contactId?: string;
            contact?: components["schemas"]["Contact"];
            isPrimary?: boolean;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            notes?: string | null;
            roles?: components["schemas"]["CompanyContactRole"][] | null;
            emails?: components["schemas"]["CompanyContactEmail"][] | null;
            phones?: components["schemas"]["CompanyContactPhone"][] | null;
        };
        CompanyContactDto: {
            /** Format: uuid */
            contactId: string;
            isPrimary?: boolean;
            notes?: string | null;
        };
        CompanyContactEmail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            companyContactId?: string;
            companyContact?: components["schemas"]["CompanyContact"];
            email?: string | null;
            isPrimary?: boolean;
            doNotEmail?: boolean;
        };
        CompanyContactPhone: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            companyContactId?: string;
            companyContact?: components["schemas"]["CompanyContact"];
            phone?: string | null;
            isPrimary?: boolean;
            doNotCall?: boolean;
        };
        CompanyContactResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            contactId?: string;
            contactName?: string | null;
            isPrimary?: boolean;
            notes?: string | null;
        };
        CompanyContactRole: {
            /** Format: uuid */
            companyContactId?: string;
            companyContact?: components["schemas"]["CompanyContact"];
            /** Format: int32 */
            roleId?: number;
            role?: components["schemas"]["Role"];
        };
        CompanyResponse: {
            /** Format: uuid */
            id?: string;
            companyName?: string | null;
            address?: string | null;
            address2?: string | null;
            city?: string | null;
            state?: string | null;
            zip?: string | null;
            country?: string | null;
            websiteUrl?: string | null;
            type?: string | null;
            taxId?: string | null;
            /** Format: date-time */
            lastUpdate?: string | null;
            collections?: boolean;
            writeOff?: boolean;
            primaryRepName?: string | null;
            legacyPrimaryCategory?: string | null;
            /** Format: int64 */
            hubspotCompanyId?: number | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            /** Format: date-time */
            createdDate?: string | null;
            isActive?: boolean;
            isNewCompany?: boolean;
            companySpecialBilling?: boolean | null;
            contacts?: components["schemas"]["CompanyContactResponse"][] | null;
        };
        Contact: {
            /** Format: uuid */
            id?: string;
            companyContacts?: components["schemas"]["CompanyContact"][] | null;
            emails?: components["schemas"]["ContactEmail"][] | null;
            firstName?: string | null;
            lastName?: string | null;
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            state?: string | null;
            zip?: string | null;
            country?: string | null;
            salutation?: string | null;
            userRepId?: string | null;
            isActive?: boolean;
            gender?: string | null;
            leadSource?: string | null;
            leadStatus?: string | null;
            hubspotId?: string | null;
            jobTitle?: string | null;
            department?: string | null;
            /** Format: date-time */
            createdDate?: string | null;
            /** Format: date-time */
            lastUpdatedDate?: string | null;
        };
        ContactCompanyDto: {
            /** Format: uuid */
            companyId: string;
            isPrimary?: boolean;
            notes?: string | null;
        };
        ContactCompanyResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            companyId?: string;
            companyName?: string | null;
            isPrimary?: boolean;
            notes?: string | null;
        };
        ContactEmail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            contactId?: string;
            contact?: components["schemas"]["Contact"];
            email?: string | null;
            isPrimary?: boolean;
            doNotEmail?: boolean;
        };
        ContactEmailDto: {
            /** Format: email */
            email: string;
            label?: string | null;
            isPrimary?: boolean;
        };
        ContactEmailResponse: {
            /** Format: uuid */
            id?: string;
            email?: string | null;
            isPrimary?: boolean;
            doNotEmail?: boolean;
        };
        ContactResponse: {
            /** Format: uuid */
            id?: string;
            firstName?: string | null;
            lastName?: string | null;
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            state?: string | null;
            zip?: string | null;
            country?: string | null;
            salutation?: string | null;
            userRepId?: string | null;
            isActive?: boolean;
            gender?: string | null;
            leadSource?: string | null;
            leadStatus?: string | null;
            hubspotId?: string | null;
            jobTitle?: string | null;
            department?: string | null;
            /** Format: date-time */
            createdDate?: string | null;
            /** Format: date-time */
            lastUpdatedDate?: string | null;
            emails?: components["schemas"]["ContactEmailResponse"][] | null;
            companies?: components["schemas"]["ContactCompanyResponse"][] | null;
        };
        CreateCompanyRequest: {
            companyName: string;
            address?: string | null;
            address2?: string | null;
            city?: string | null;
            state?: string | null;
            zip?: string | null;
            country?: string | null;
            websiteUrl?: string | null;
            type?: string | null;
            taxId?: string | null;
            collections?: boolean;
            writeOff?: boolean;
            primaryRepName?: string | null;
            legacyPrimaryCategory?: string | null;
            /** Format: int64 */
            hubspotCompanyId?: number | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            isActive?: boolean;
            isNewCompany?: boolean;
            companySpecialBilling?: boolean | null;
            contacts?: components["schemas"]["CompanyContactDto"][] | null;
        };
        CreateContactRequest: {
            firstName: string;
            lastName: string;
            addressLine1?: string | null;
            addressLine2?: string | null;
            city?: string | null;
            state?: string | null;
            zip?: string | null;
            country?: string | null;
            salutation?: string | null;
            userRepId?: string | null;
            isActive?: boolean;
            gender?: string | null;
            leadSource?: string | null;
            leadStatus?: string | null;
            hubspotId?: string | null;
            jobTitle?: string | null;
            department?: string | null;
            emails?: components["schemas"]["ContactEmailDto"][] | null;
            companies?: components["schemas"]["ContactCompanyDto"][] | null;
        };
        CreateIntegrationRequest: {
            provider: string;
            category: components["schemas"]["IntegrationCategory"];
            displayName: string;
            isActive?: boolean;
            status?: string | null;
            authType: string;
            metadataJson?: string | null;
        };
        /** @enum {string} */
        IntegrationCategory: "EmailMarketing";
        IntegrationResponse: {
            /** Format: uuid */
            id?: string;
            provider?: string | null;
            category?: components["schemas"]["IntegrationCategory"];
            displayName?: string | null;
            isActive?: boolean;
            status?: string | null;
            authType?: string | null;
            metadataJson?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Role: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            isSystem?: boolean;
            companyContactRoles?: components["schemas"]["CompanyContactRole"][] | null;
        };
        SendEmailRequest: {
            /** Format: uuid */
            integrationId: string;
            /** Format: email */
            toEmail: string;
            subject: string;
            htmlBody: string;
        };
        SendEmailResponse: {
            success?: boolean;
            provider?: string | null;
            message?: string | null;
            providerStatus?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
